context("Checking data file")
test_that("File and folder exists", {
  skip('only test 2')
  expect_error(appsilon.loadData('../../data/nocsvfile.csv'))
  expect_true(appsilon.loadData('../../data/ships.csv'))
  expect_equal(length(colnames(vessels)), 20)
  expect_equal(colnames(vessels)[1], 'LAT')
  expect_equal(colnames(vessels)[2], 'LON')
  expect_equal(colnames(vessels)[3], 'SPEED')
  expect_equal(colnames(vessels)[4], 'COURSE')
  expect_equal(colnames(vessels)[5], 'HEADING')
  expect_equal(colnames(vessels)[6], 'DESTINATION')
  expect_equal(colnames(vessels)[7], 'FLAG')
  expect_equal(colnames(vessels)[8], 'LENGTH')
  expect_equal(colnames(vessels)[9], 'SHIPNAME')
  expect_equal(colnames(vessels)[10], 'SHIPTYPE')
  expect_equal(colnames(vessels)[11], 'SHIP_ID')
  expect_equal(colnames(vessels)[12], 'WIDTH')
  expect_equal(colnames(vessels)[13], 'DWT')
  expect_equal(colnames(vessels)[14], 'DATETIME')
  expect_equal(colnames(vessels)[15], 'PORT')
  expect_equal(colnames(vessels)[16], 'date')
  expect_equal(colnames(vessels)[17], 'week_nb')
  expect_equal(colnames(vessels)[18], 'ship_type')
  expect_equal(colnames(vessels)[19], 'port')
  expect_equal(colnames(vessels)[20], 'is_parked')
})